autonomy_level: 3
autonomy_level: 4
limits:
  max_changed_files: 10
  max_changed_lines: 40
protected_paths:
  - "**/security/**"
  - "**/*.spec.*"
  - "**/public-api/**"
merge_policy:
  require_shadow_ci: true
  allow_src_changes: codemod-only
risk_budget:
  daily_tokens: 5
  codemod_cost: 2
notes:
  - "Codemod PRs must pass smoke & public API checks before merge."
  - "See scripts/tests/smoke.mjs and scripts/guards/public-api-check.mjs."
