governor:
studio:
autonomy: 1
riskBudget:
  maxLinesPerPatch: 40
  maxPatchesPerRun: 3
  maxFilesTouched: 10
  tokensPerDay: 8
protected:
  - "**/security/**"
  - "**/*.spec.*"
  - "**/public-api/**"
bans:
  lockfiles:
    - "yarn.lock"
    - "package-lock.json"
  deepImports:
    - "**/internal/**"
shadow:
  matrix:
    - node18
    - node20
governor:
  prsPerDay: 2
  ciMinutesPerHour: 30
  maxConcurrentShadows: 2
