version: '3.7'
services:
  temporal:
    image: temporalio/auto-setup:1.21
    environment:
      - DB=sqlite
      - TEMPORAL_UI_ENABLED=true
    ports:
      - "7233:7233"
      - "8233:8233"
  temporal-ui:
    image: temporalio/ui:2.16
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
    ports:
      - "8080:8080"
