name: CI
on:
  pull_request:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm -w build || true
      - name: Lint
        run: pnpm -w lint || true
      - name: Type-check
        run: pnpm -w run -r type-check || true