const { execSync } = require('child_process');
const fs = require('fs'); const path = require('path');
function sh(cmd){ try{ return execSync(cmd,{stdio:'pipe'}).toString(); } catch(e){ return e.stdout?.toString()||''; } }
fs.mkdirSync('reports/doctor', { recursive: true });
const dirty = sh('git status --porcelain').trim().length>0;
if(dirty) sh('git stash -k -u');
// try eslint fix if present
sh('npx -y eslint . --fix || true');
// add more safe fixes here later (prettier, sort, etc.)

const patchPath = path.join('reports','doctor','patch.diff');
let diff = sh('git diff');
if (diff && diff.trim()) {
  fs.writeFileSync(patchPath, diff);
  // revert changes so runner stays advice-only
  sh('git checkout -- .');
} else {
  fs.writeFileSync(patchPath, '# no-op patch: Doctor found no changes\n');
}
fs.writeFileSync(path.join('reports','doctor','README.txt'),
  'Artifacts generated by ODAVL Doctor.\n- patch.diff: may be a no-op if no fixes were available.\n');
if(dirty) sh('git stash pop || true');
console.log('doctor-heal: patch.diff exists:', fs.existsSync(patchPath));
