name: Attestation
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: mkdir -p reports
      - run: node scripts/attest.mjs
      - uses: actions/upload-artifact@v4
        with:
          name: attestation
          path: reports/attestation.json
