name: Auto Rollback
on:
  workflow_run:
    workflows: ["Freeze Audit"]
    types:
      - completed
jobs:
  auto-rollback:
    if: github.event.workflow_run.conclusion == 'failure' && github.event.workflow_run.event == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Find last auto-merge commit
        run: |
          echo "TODO: find last auto-merge commit, revert, and open PR"
          exit 0
