name: CI
on:
  pull_request:
  push:
    branches:
      - '**'
defaults:
  run:
    working-directory: odavl_studio
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: Build (workspace)
        run: pnpm -w build || true
      - name: Lint (golden-repo)
        run: pnpm --filter golden-repo exec eslint . -f stylish || true
      - name: Type-check (workspace)
        run: pnpm -w run -r type-check || true