name: CI
on:
  pull_request:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm -w -r run build || true
      - name: Type
        run: pnpm -w -r run type-check || pnpm exec tsc --noEmit || true
      - name: Lint
        run: pnpm -w -r run lint || true
