
name: CI
on:
  pull_request:
  push:
    branches:
      - "**"
  workflow_dispatch:
jobs:

  build:
    continue-on-error: false
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 10.17.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
          cache-dependency-path: pnpm-lock.yaml
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Build
        run: pnpm -w -r run build || true
      - name: Type
        run: pnpm -w -r run type-check || pnpm exec tsc --noEmit || true
      - name: Lint
        run: pnpm -w -r run lint || true


  security-sbom:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM (pnpm fallback)
        shell: pwsh
        run: pnpm list --json --recursive > reports/phase3/security/sbom.cdx.json
      - name: Archive SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom-evidence
          path: reports/phase3/security/sbom.cdx.json

  security-osv:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Archive OSV log (fallback)
        uses: actions/upload-artifact@v4
        with:
          name: osv-evidence
          path: reports/phase3/security/osv.log

  security-gitleaks:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Archive Gitleaks log (fallback)
        uses: actions/upload-artifact@v4
        with:
          name: gitleaks-evidence
          path: reports/phase3/security/gitleaks.log
