name: ODAVL CI Doctor
on:
  workflow_run:
    workflows: ["CI","Go CI (W5)","Java CI (W5)"]
    types: [completed]
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
permissions:
  contents: read
  actions: read
  checks: write
  security-events: write
  pull-requests: write
concurrency:
  group: doctor-${{ github.event.workflow_run.head_branch || github.ref }}
  cancel-in-progress: true
jobs:
  run-doctor:
    if: >
      (github.event_name != 'workflow_run') ||
      (github.event.workflow_run.conclusion == 'failure' &&
       !startsWith(github.event.workflow_run.head_branch, 'odavl/doctor-'))
    runs-on: ubuntu-latest
    steps:
      - name: Cap attempts per SHA
        if: ${{ github.event_name == 'workflow_run' }}
        id: cap
        env:
          GH_TOKEN: ${{ github.token }}
          SHA: ${{ github.event.workflow_run.head_sha }}
        run: |
          COUNT=$(gh api repos/${GITHUB_REPOSITORY}/actions/runs --paginate -q '.workflow_runs[] | select(.name=="ODAVL CI Doctor" and .head_sha=="'$SHA'") | .id' | wc -l | xargs)
          echo "count=$COUNT" >> $GITHUB_OUTPUT
      - uses: ./.github/actions/odavl-doctor-runner
        if: ${{ !steps.cap.outputs.count || steps.cap.outputs.count < '2' }}
        with:
          mode: advice
          max_files: 10
          max_lines: 40
          protected_paths: "**/security/**,**/*.spec.*,**/public-api/**"
          task_name: "ci-heal"
      - name: Download doctor artifacts
        if: ${{ !steps.cap.outputs.count || steps.cap.outputs.count < '2' }}
        uses: actions/download-artifact@v4
        with:
          name: doctor-artifacts
          path: reports/doctor
      - name: Shadow Verify (ephemeral apply & test)
        if: ${{ hashFiles('reports/doctor/patch.diff') != '' }}
        id: shadow
        shell: bash
        run: |
          set -e
          git apply --check reports/doctor/patch.diff
          git apply reports/doctor/patch.diff
          pnpm install --frozen-lockfile || pnpm install
          (pnpm -w run build || true) 2>&1 | tee -a reports/doctor/shadow-verify.txt
          (pnpm -w run lint --if-present || true) 2>&1 | tee -a reports/doctor/shadow-verify.txt
          (pnpm -w run typecheck --if-present || true) 2>&1 | tee -a reports/doctor/shadow-verify.txt
          (pnpm -w run test --if-present || true) 2>&1 | tee -a reports/doctor/shadow-verify.txt
        continue-on-error: true
      - name: Revert patch
        if: ${{ steps.shadow.outcome != '' }}
        run: git reset --hard
      - name: Upload shadow verify logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: doctor-shadow-verify
          path: reports/doctor/shadow-verify.txt
          if-no-files-found: ignore
      - name: Label PR as needs-human (on shadow fail or cap)
        if: ${{ (steps.shadow.outcome == 'failure') || (steps.cap.outputs.count && steps.cap.outputs.count >= '2') }}
        env:
          GH_TOKEN: ${{ github.token }}
          SHA: ${{ github.event.workflow_run.head_sha || github.sha }}
        shell: bash
        run: |
          PR=$(gh pr list --search "$SHA" --state open --json number -q '.[0].number' || echo "")
          if [ -n "$PR" ]; then gh pr edit "$PR" --add-label "needs-human"; fi
