name: ODAVL CI Doctor
on:
  workflow_run:
    workflows: ["CI","Go CI (W5)","Java CI (W5)"]
    types: [completed]
  workflow_dispatch:
  pull_request:
    branches: ["odavl/ci-doctor-smoke-20250926"]
  schedule:
    - cron: "0 3 * * *"
permissions:
  contents: read
  actions: read
  checks: write
  security-events: write
  pull-requests: write
concurrency:
  group: doctor-${{ github.event.workflow_run.head_branch || github.ref }}
  cancel-in-progress: true
jobs:
  run-doctor:
    if: >
      (github.event_name != 'workflow_run') ||
      (github.event.workflow_run.conclusion == 'failure' &&
       !startsWith(github.event.workflow_run.head_branch, 'odavl/doctor-'))
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: {fetch-depth: 0}
      - uses: ./.github/actions/odavl-doctor-runner
        with:
          mode: advice
          max_files: 10
          max_lines: 40
          protected_paths: "**/security/**,**/*.spec.*,**/public-api/**"
          task_name: "ci-heal"
