<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 86b1346 (H3: Safe delete (quarantine) of LEGACY and NOISE files with full evidence. See reports/hygiene/2025-10-01/run-1/ for audit trail.)
name: Freeze Pipeline
on:
  workflow_dispatch:
jobs:
  freeze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lock Dependencies
        run: |
          cp pnpm-lock.yaml reports/evaluations/2025-10-01/governance/pnpm-lock.freeze.yaml
          cp package.json reports/evaluations/2025-10-01/governance/package.freeze.json
      - name: Archive Freeze Evidence
        uses: actions/upload-artifact@v4
        with:
          name: freeze-evidence
          path: reports/evaluations/2025-10-01/governance/*.freeze.*name: Freeze Audit
<<<<<<< HEAD
=======
name: Freeze Audit
>>>>>>> 9fe4bd7 (chore: bootstrap ODAVL Studio repository)
=======
>>>>>>> 86b1346 (H3: Safe delete (quarantine) of LEGACY and NOISE files with full evidence. See reports/hygiene/2025-10-01/run-1/ for audit trail.)
on:
  workflow_dispatch:
  name: Freeze Audit
  on:
    workflow_dispatch:
    name: Freeze Audit
    on:
      workflow_dispatch:
      pull_request:
    jobs:
      freeze:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - run: mkdir -p reports
          - run: node scripts/freeze-audit.mjs
          - uses: actions/upload-artifact@v4
            with:
              name: final-audit
              path: |
                reports/final-audit.json
                reports/final-audit.md
