name: ODAVL CI Doctor
on:
  workflow_dispatch:
permissions:
  contents: read
  actions: read
  checks: write
  security-events: write
  pull-requests: write
jobs:
  registered:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Doctor workflow registered (placeholder)."
