name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        run: npm install -g pnpm@8
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build CLI
        run: pnpm --filter @odavl/cli run build
      - name: Pack CLI
        run: cd apps/cli && npm pack
      - name: Upload CLI artifact
        uses: actions/upload-artifact@v4
        with:
          name: odavl-cli-tarball
          path: apps/cli/odavl-cli-*.tgz
          # Base release command
          RELEASE_CMD="gh release create ${{ steps.version.outputs.version }} \
            --title \"ODAVL Studio ${{ steps.version.outputs.version }}\" \
            --notes-file ${{ steps.changelog.outputs.changes_file }}"

          # Add QA report if it exists
          if [ "${{ steps.qa_report.outputs.qa_exists }}" = "true" ]; then
            RELEASE_CMD="$RELEASE_CMD ${{ steps.qa_report.outputs.qa_file }}"
          fi

          # Execute release creation
          eval $RELEASE_CMD

      - name: Release Summary
        run: |
          echo "🚀 Release ${{ steps.version.outputs.version }} created successfully!"
          echo "📋 Changelog: ${{ steps.changelog.outputs.changes_file }}"
          if [ "${{ steps.qa_report.outputs.qa_exists }}" = "true" ]; then
            echo "📊 QA Report: ${{ steps.qa_report.outputs.qa_file }}"
          fi
