name: Secure CI
on:
<<<<<<< HEAD
  workflow_dispatch:
=======
>>>>>>> 9fe4bd7 (chore: bootstrap ODAVL Studio repository)
  pull_request:
  push:
    branches: [main]
jobs:
  semgrep:
<<<<<<< HEAD
    continue-on-error: false
=======
>>>>>>> 9fe4bd7 (chore: bootstrap ODAVL Studio repository)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install semgrep
      - run: semgrep ci --config p/ci --error --timeout 600
  gitleaks:
<<<<<<< HEAD
    continue-on-error: false
=======
>>>>>>> 9fe4bd7 (chore: bootstrap ODAVL Studio repository)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          curl -sSL https://raw.githubusercontent.com/gitleaks/gitleaks/master/install.sh | bash
          ./gitleaks detect -v --redact --exit-code 1
  osv_scanner:
<<<<<<< HEAD
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install -g osv-scanner gitleaks
      - run: osv-scanner --skip-git
      - run: gitleaks detect --no-banner
=======
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
>>>>>>> 9fe4bd7 (chore: bootstrap ODAVL Studio repository)
      - run: |
          curl -sSL https://raw.githubusercontent.com/google/osv-scanner/main/scripts/install.sh | sh -s -- -b /usr/local/bin
          mkdir -p reports/security
          osv-scanner -r . --format json > reports/security/osv.json || true
          jq -e '[.vulnerabilities[]?|select(.severity|inside(["HIGH","CRITICAL"]))] | length==0' reports/security/osv.json
<<<<<<< HEAD
  sbom:
    continue-on-error: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install CycloneDX toolchain
        run: npm install -g @cyclonedx/cyclonedx-npm
      - name: Generate SBOM (CycloneDX)
        run: cyclonedx-npm --output-format json --output-file sbom.json
      - name: Upload SBOM artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json
=======
>>>>>>> 9fe4bd7 (chore: bootstrap ODAVL Studio repository)
