name: VSCode Smoke
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pnpm install
      - run: mkdir -p reports/evidence
      - run: node scripts/vscode-smoke.mjs
      - uses: actions/upload-artifact@v4
        with:
          name: vscode-smoke
          path: reports/evidence/vscode-smoke.log
